# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/u8800pro/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/huawei/u8800pro/proprietary/bin/modempre:system/bin/modempre \
    vendor/huawei/u8800pro/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/huawei/u8800pro/proprietary/bin/oem_rpc_svc:system/bin/oem_rpc_svc \
    vendor/huawei/u8800pro/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/huawei/u8800pro/proprietary/etc/wifi/bcmdhd.cal:system/etc/wifi/bcmdhd.cal \
    vendor/huawei/u8800pro/proprietary/lib/libauth.so:system/lib/libauth.so \
    vendor/huawei/u8800pro/proprietary/lib/libchromatix_ov5647_sunny_default_video.so:system/lib/libchromatix_ov5647_sunny_default_video.so \
    vendor/huawei/u8800pro/proprietary/lib/libchromatix_ov5647_sunny_preview.so:system/lib/libchromatix_ov5647_sunny_preview.so \
    vendor/huawei/u8800pro/proprietary/lib/libchromatix_s5k4e1gx_p_default_video.so:system/lib/libchromatix_s5k4e1gx_p_default_video.so \
    vendor/huawei/u8800pro/proprietary/lib/libchromatix_s5k4e1gx_p_preview.so:system/lib/libchromatix_s5k4e1gx_p_preview.so \
    vendor/huawei/u8800pro/proprietary/lib/libcm.so:system/lib/libcm.so \
    vendor/huawei/u8800pro/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/huawei/u8800pro/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/huawei/u8800pro/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/huawei/u8800pro/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/huawei/u8800pro/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    vendor/huawei/u8800pro/proprietary/lib/libhwrpc.so:system/lib/libhwrpc.so \
    vendor/huawei/u8800pro/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/huawei/u8800pro/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/huawei/u8800pro/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/huawei/u8800pro/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/huawei/u8800pro/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/huawei/u8800pro/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/huawei/u8800pro/proprietary/lib/liboem_rapi.so:system/lib/liboem_rapi.so \
    vendor/huawei/u8800pro/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/huawei/u8800pro/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/huawei/u8800pro/proprietary/lib/libqdi.so:system/lib/libqdi.so \
    vendor/huawei/u8800pro/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/huawei/u8800pro/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/huawei/u8800pro/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/huawei/u8800pro/proprietary/lib/libqueue.so:system/lib/libqueue.so \
    vendor/huawei/u8800pro/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/huawei/u8800pro/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/huawei/u8800pro/proprietary/lib/libwms.so:system/lib/libwms.so \
    vendor/huawei/u8800pro/proprietary/lib/libwmsts.so:system/lib/libwmsts.so \
    vendor/huawei/u8800pro/proprietary/vendor/firmware/bcm4329.hcd:system/vendor/firmware/bcm4329.hcd

PRODUCT_PACKAGES += \
    libaudcal \
    libaudioalsa
